// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image6":
            case "Grassy Terrain Skeleton King":return img`
........................
........................
........5.5.............
.......5.5..............
......5.55ffff..........
.....5.55f7777ff........
......55b777777bf.......
.....5.f77777777f.......
......fd77777777df......
......fd77777777df......
......fddd7777dddf......
......fbdbfddfbdbf......
......fcdcf77fcdcf......
.......fb777777bf.......
......fffcdb7bdffff.....
....fc777cbfbfc777cf....
....f7b7b7ffff7b7b7f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image7":
            case "Nether Skeleton King":return img`
........................
........................
........5.5.............
.......5.5..............
......5.55ffff..........
.....5.55f2222ff........
......55c222222cf.......
.....5.f22222222f.......
......fb22222222bf......
......fb22222222bf......
......fbbb2222bbbf......
......fcbcfbbfcbcf......
......febef22febef......
.......fc222222cf.......
......fffebc2cbffff.....
....fe222ecfcfe222ef....
....f2c2c2ffff2c2c2f....
....fcfcffffffcfcfcf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image1":
            case "Player1":return img`
. . . . . . . . . . . . . . . . 
. . . . c c c c . . . . . . . . 
. . c c 5 5 5 5 c c . . . . . . 
. c 5 5 5 5 5 5 5 5 c . . . . . 
c 5 5 5 5 5 1 f 5 5 5 c . . . . 
c 5 5 5 5 5 f f 5 5 5 5 c . . . 
c 5 5 5 5 5 5 5 5 5 5 5 c . . . 
c c b b 1 b 5 5 5 5 5 5 d c . . 
c 5 3 3 3 5 5 5 5 5 d d d c . . 
. b 5 5 5 5 5 5 5 5 d d d c . . 
. . c b b c 5 5 b d d d d c c . 
. c b b c 5 5 b b d d d d c d c 
. c c c c c c d d d d d d d d c 
. . . c c c c d 5 5 b d d d c . 
. . c c c c c b 5 5 b c c c . . 
. . c b b b c d 5 5 b c . . . . 
`;
            case "image5":
            case "Dungeon Skeleton King":return img`
........................
........................
........5.5.............
.......5.5..............
......5.55ffff..........
.....5.55f1111ff........
......55b111111bf.......
.....5.f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image11":
            case "Nether Rat":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
e . . . . . . . . . e . . . . . 
. e . . . . . . . 2 3 e . . . . 
. 2 . . . . . . . 2 2 2 . . . . 
. 2 e . . . . . e 2 2 f 2 . . . 
. . 2 . e e e 2 2 2 2 2 2 3 . . 
. . . e 2 2 2 2 2 2 2 2 e . . . 
. . . 2 2 2 e 2 2 e 2 2 . . . . 
. . . 2 . e . . 2 . e . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image13":
            case "Nether Bat":return img`
. . f f f . . . . . . . . f f f 
. f f e e . . . . . . f e 2 2 e 
f f e e . . . . . . f e 2 2 e . 
f e f e . . . . . . f 2 e e e . 
f f f e e . e e . f e 2 2 e e . 
f f e 3 e e 3 e e f 2 e 2 2 e . 
f f 2 3 2 e 3 2 e f 2 e e 2 e . 
. e 2 2 2 2 2 2 e 2 2 e e e . . 
. e 1 2 2 2 1 2 2 e e e e . . . 
e 2 2 2 2 2 2 2 2 2 e e . . . . 
e 2 e 2 2 2 e 2 2 2 2 f . . . . 
f 2 1 f f f 1 2 2 2 2 f e . . . 
f 2 2 2 2 2 2 2 2 2 2 f e e . . 
. f 2 2 2 2 2 2 2 2 e f . . . . 
. . f 2 2 2 2 2 2 e f . . . . . 
. . . f f f f f f f . . . . . . 
`;
            case "image17":
            case "Nether Snake":return img`
. . . . e e e e e e . . . . . . 
. . . e 4 2 2 2 2 4 e . . . . . 
. . e 2 2 2 2 2 2 2 2 e . . . . 
. e 4 2 2 2 2 2 2 2 2 4 e . . . 
. e 2 e 4 4 4 4 e 2 2 2 e . . . 
. f 2 4 f 4 4 f 4 2 2 2 f . . . 
. f 2 2 2 2 2 2 2 2 2 2 f . . . 
. . f 2 2 2 2 4 e 2 2 4 f e . . 
. . . f e e e e 2 2 4 f 2 2 e . 
. . e 2 3 2 2 2 4 e f 2 2 2 2 e 
. e 2 2 3 2 2 e f e 4 2 2 4 e e 
e 1 1 1 1 2 4 f e e 4 4 4 e . . 
f 1 1 1 1 1 4 4 e 4 4 4 4 f . . 
f 4 1 1 1 1 1 4 4 4 4 4 e f . . 
. f 4 1 1 1 1 1 1 4 4 4 f . . . 
. . e e e e e e e e e f . . . . 
`;
            case "image10":
            case "Grassy Rat":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
6 . . . . . . . . . 6 . . . . . 
. 6 . . . . . . . 7 3 6 . . . . 
. 7 . . . . . . . 7 7 7 . . . . 
. 7 6 . . . . . 6 7 7 f 7 . . . 
. . 7 . 6 6 6 7 7 7 7 7 7 3 . . 
. . . 6 7 7 7 7 7 7 7 7 6 . . . 
. . . 7 7 7 6 7 7 6 7 7 . . . . 
. . . 7 . 6 . . 7 . 6 . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image12":
            case "Grassy Bat":return img`
. . f f f . . . . . . . . f f f 
. f f 6 6 . . . . . . f 6 7 7 6 
f f 6 6 . . . . . . f 6 7 7 6 . 
f 6 f 6 . . . . . . f 7 6 6 6 . 
f f f 6 6 . 6 6 . f 6 7 7 6 6 . 
f f 6 3 6 6 3 6 6 f 7 6 7 7 6 . 
f f 7 3 7 6 3 7 6 f 7 6 6 7 6 . 
. 6 7 7 7 7 7 7 6 7 7 6 6 6 . . 
. 6 1 7 7 7 1 7 7 6 6 6 6 . . . 
6 7 7 7 7 7 7 7 7 7 6 6 . . . . 
6 7 6 7 7 7 6 7 7 7 7 f . . . . 
f 7 1 f f f 1 7 7 7 7 f 6 . . . 
f 7 7 7 7 7 7 7 7 7 7 f 6 6 . . 
. f 7 7 7 7 7 7 7 7 6 f . . . . 
. . f 7 7 7 7 7 7 6 f . . . . . 
. . . f f f f f f f . . . . . . 
`;
            case "image16":
            case "Grassy Snake":return img`
. . . . c c c c c c . . . . . . 
. . . c 6 7 7 7 7 6 c . . . . . 
. . c 7 7 7 7 7 7 7 7 c . . . . 
. c 6 7 7 7 7 7 7 7 7 6 c . . . 
. c 7 c 6 6 6 6 c 7 7 7 c . . . 
. f 7 6 f 6 6 f 6 7 7 7 f . . . 
. f 7 7 7 7 7 7 7 7 7 7 f . . . 
. . f 7 7 7 7 6 c 7 7 6 f c . . 
. . . f c c c c 7 7 6 f 7 7 c . 
. . c 7 2 7 7 7 6 c f 7 7 7 7 c 
. c 7 7 2 7 7 c f c 6 7 7 6 c c 
c 1 1 1 1 7 6 f c c 6 6 6 c . . 
f 1 1 1 1 1 6 6 c 6 6 6 6 f . . 
f 6 1 1 1 1 1 6 6 6 6 6 c f . . 
. f 6 1 1 1 1 1 1 6 6 6 f . . . 
. . c c c c c c c c c f . . . . 
`;
            case "image8":
            case "Dungeon Rat":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
c . . . . . . . . . c . . . . . 
. c . . . . . . . b 3 c . . . . 
. b . . . . . . . b b b . . . . 
. b c . . . . . c b b f b . . . 
. . b . c c c b b b b b b 3 . . 
. . . c b b b b b b b b c . . . 
. . . b b b c b b c b b . . . . 
. . . b . c . . b . c . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image9":
            case "Dungeon Bat":return img`
. . f f f . . . . . . . . f f f 
. f f c c . . . . . . f c b b c 
f f c c . . . . . . f c b b c . 
f c f c . . . . . . f b c c c . 
f f f c c . c c . f c b b c c . 
f f c 3 c c 3 c c f b c b b c . 
f f b 3 b c 3 b c f b c c b c . 
. c b b b b b b c b b c c c . . 
. c 1 b b b 1 b b c c c c . . . 
c b b b b b b b b b c c . . . . 
c b c b b b c b b b b f . . . . 
f b 1 f f f 1 b b b b f c . . . 
f b b b b b b b b b b f c c . . 
. f b b b b b b b b c f . . . . 
. . f b b b b b b c f . . . . . 
. . . f f f f f f f . . . . . . 
`;
            case "image15":
            case "Dungeon Snake":return img`
. . . . c c c c c c . . . . . . 
. . . c e d d d d e c . . . . . 
. . c d d d d d d d d c . . . . 
. c e d d d d d d d d e c . . . 
. c d c e e e e c d d d c . . . 
. f d e f e e f e d d d f . . . 
. f d d d d d d d d d d f . . . 
. . f d d d d e c d d e f c . . 
. . . f c c c c d d e f d d c . 
. . c d 2 d d d e c f d d d d c 
. c d d 2 d d c f c e d d e c c 
c 1 1 1 1 d e f c c e e e c . . 
f 1 1 1 1 1 e e c e e e e f . . 
f e 1 1 1 1 1 e e e e e c f . . 
. f e 1 1 1 1 1 1 e e e f . . . 
. . c c c c c c c c c f . . . . 
`;
            case "image2":
            case "Injured Dungeon Skeleton":return img`
........................
........................
........................
........................
..........ffff..........
........ff113fff........
.......fb11133fff.......
.......f11111333f.......
......fd11111113ff......
......fd11111111df......
......fddd1111dddf......
......fbdf1dd1fdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image14":
            case "Dungeon Skeleton":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image4":
            case "Nether Skeleton":return img`
........................
........................
........................
........................
..........ffff..........
........ff2222ff........
.......fc222222cf.......
.......f22222222f.......
......fb22222222bf......
......fb22222222bf......
......fbbb2222bbbf......
......fcbcfbbfcbcf......
......febef22febef......
.......fc222222cf.......
......fffebc2cbffff.....
....fe222ecfcfe222ef....
....f2c2c2ffff2c2c2f....
....fcfcffffffcfcfcf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image3":
            case "Grassy Terrain Skeleton":return img`
........................
........................
........................
........................
..........ffff..........
........ff7777ff........
.......fb777777bf.......
.......f77777777f.......
......fd77777777df......
......fd77777777df......
......fddd7777dddf......
......fbdbfddfbdbf......
......fcdcf77fcdcf......
.......fb777777bf.......
......fffcdb7bdffff.....
....fc777cbfbfc777cf....
....f7b7b7ffff7b7b7f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image18":
            case "Key":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . 5 5 d . . . . . . . . . . 
. . . d 4 5 5 d 5 5 d . . . . . 
. . . . 5 d . . 4 . 4 . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
